In [1]:
import numpy as np

In [2]:
array=[1,2,3,4,5];

In [3]:
np.mean(array)

3.0

In [4]:
np.median(array)

3.0

In [5]:
np.std(array)

1.4142135623730951

In [12]:
if True:
    array=np.array([[1,2,3],[4,5,6]],float)
    print(array)
    print("")
    array=np.array([12,45,34,5.0],float)
    print(array)
    print(array[1])
    print(array[:2])
    print(array[:-1])
    array[1]=5.0
    print(array[1])

[[1. 2. 3.]
 [4. 5. 6.]]

[12. 45. 34.  5.]
45.0
[12. 45.]
[12. 45. 34.]
5.0


In [15]:
array1=np.array([1,2,3],float)
array2=np.array([4,5,6],float)
print(array1-array2)
print(array1*array2)

[-3. -3. -3.]
[ 4. 10. 18.]


In [20]:
array1=np.array([1,2,3],float)
array2=np.array([[3],[5],[4]],float)
print(array1)
print(array2)
print(np.dot(array1,array2))

[1. 2. 3.]
[[3.]
 [5.]
 [4.]]
[25.]
